'use client'

import { useLang } from '@/context/LangContext'

const content = {
  pt: {
    sections: [
      {
        title: 'O Problema com Dados Não Validados',
        body: <>
          <p>Em sistemas de ingestão de dados, o maior inimigo não é o volume — é a inconsistência silenciosa. Um campo que deveria ser <code>float</code> chega como <code>string</code>. Uma data que deveria ser ISO 8601 chega com fuso horário errado. Sem validação na entrada, esse lixo propaga por todo o pipeline.</p>
          <p>Por muito tempo, usei Pydantic v1 com FastAPI e achei que estava coberto. Estava. Mas quando migrei para v2, percebi o quanto estava deixando na mesa em termos de performance e expressividade.</p>
        </>,
      },
      {
        title: 'O Que Mudou no v2',
        body: <>
          <p>Pydantic v2 reescreveu o core em Rust. O resultado prático: validação <strong>5 a 50× mais rápida</strong> dependendo do schema. Para um endpoint que recebia 500 requisições/minuto com payloads de ~30 campos, isso foi de 12ms para 2.4ms de overhead de validação.</p>
          <p>Além da velocidade, a API ficou mais explícita. O decorador <code>@field_validator</code> substituiu os métodos <code>@validator</code> com semântica mais clara. E o <code>model_config</code> consolidou tudo que antes ficava espalhado em <code>class Config</code>.</p>
        </>,
      },
      {
        title: 'Padrões que Passei a Usar',
        body: <>
          <p>O principal ganho de expressividade foi com tipos customizados. Em vez de validar um CPF com regex num <code>@field_validator</code>, criei um tipo <code>CPFStr</code> reutilizável com <code>Annotated</code> e <code>AfterValidator</code> — o schema OpenAPI gerado pelo FastAPI inclusive documenta a constraint automaticamente.</p>
          <p>Outro padrão que adotei: <code>model_validator(mode='before')</code> para normalizar dados antes da validação de campos. Endereços com formatação inconsistente, strings com espaços extras, datas em múltiplos formatos — tudo normalizado num único lugar antes de qualquer validação.</p>
        </>,
      },
      {
        title: 'Vale o Refactor?',
        body: <>
          <p>Para serviços novos, sim — comece em v2 e nunca olhe para trás. Para serviços existentes com v1, depende do volume. Se você tem endpoints que recebem dados externos (webhook, upload de arquivo, integração com terceiro), a migração se paga rápido. Se é só uma API interna com tipos simples, o custo do refactor pode não compensar.</p>
          <p>No meu caso, o serviço migrado processava dados de um formulário público. Após a migração, os erros de runtime em produção caíram de ~3 por semana para zero nos 3 meses seguintes. Não é glamour, mas é o que faz software durar.</p>
        </>,
      },
    ],
  },
  en: {
    sections: [
      {
        title: 'The Problem with Unvalidated Data',
        body: <>
          <p>In data ingestion systems, the biggest enemy isn't volume — it's silent inconsistency. A field that should be a <code>float</code> arrives as a <code>string</code>. A date that should be ISO 8601 arrives with the wrong timezone. Without input validation, that garbage propagates through the entire pipeline.</p>
          <p>For a long time, I used Pydantic v1 with FastAPI and thought I was covered. I was. But when I migrated to v2, I realized how much I was leaving on the table in terms of performance and expressiveness.</p>
        </>,
      },
      {
        title: 'What Changed in v2',
        body: <>
          <p>Pydantic v2 rewrote the core in Rust. The practical result: validation <strong>5 to 50× faster</strong> depending on the schema. For an endpoint receiving 500 requests/minute with ~30-field payloads, that went from 12ms to 2.4ms of validation overhead.</p>
          <p>Beyond speed, the API became more explicit. The <code>@field_validator</code> decorator replaced <code>@validator</code> methods with clearer semantics. And <code>model_config</code> consolidated everything that previously was scattered in <code>class Config</code>.</p>
        </>,
      },
      {
        title: 'Patterns I Started Using',
        body: <>
          <p>The main expressiveness gain was with custom types. Instead of validating a Brazilian CPF with regex in a <code>@field_validator</code>, I created a reusable <code>CPFStr</code> type with <code>Annotated</code> and <code>AfterValidator</code> — the OpenAPI schema generated by FastAPI even documents the constraint automatically.</p>
          <p>Another pattern I adopted: <code>model_validator(mode='before')</code> to normalize data before field validation. Inconsistently formatted addresses, strings with extra spaces, dates in multiple formats — all normalized in one place before any validation.</p>
        </>,
      },
      {
        title: 'Is the Refactor Worth It?',
        body: <>
          <p>For new services, yes — start on v2 and never look back. For existing v1 services, it depends on volume. If you have endpoints receiving external data (webhook, file upload, third-party integration), the migration pays off quickly. If it's just an internal API with simple types, the refactor cost may not be worth it.</p>
          <p>In my case, the migrated service processed data from a public form. After the migration, runtime errors in production dropped from ~3 per week to zero over the following 3 months. Not glamorous, but that's what makes software last.</p>
        </>,
      },
    ],
  },
}

export default function PydanticV2FastAPI() {
  const { lang } = useLang()
  const c = content[lang]
  return (
    <>
      {c.sections.map((s, i) => (
        <div key={i} style={{ marginBottom: '48px' }}>
          <h2 style={{
            fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 500,
            color: 'var(--blue)', letterSpacing: '0.08em', textTransform: 'uppercase',
            marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px',
          }}>
            <span style={{ color: 'var(--text3)', fontSize: '11px' }}>0{i + 1}</span>
            {s.title}
          </h2>
          <div style={{ fontSize: '14px', color: 'var(--text2)', lineHeight: 1.95 }}>
            {s.body}
          </div>
        </div>
      ))}
    </>
  )
}
